Add macOS CI
RamenDR/ramen pull request #1556
Opened 2024-09-13 00:56 UTC by nirs

Github provides macOS M1 based runners[1]. These are good enough to run 
one test cluster for testing drenv itself. Unfortunately the runners are 
virtualized and nested virtualization is not supported. If we try to
start a lima vm we fail with:

    Error Domain=VZErrorDomain Code=2 Description=\"Invalid virtual
    machine configuration.  Virtualization is not available on this
    hardware.\"

We can run drenv and ramenctl linters and test that do not require a
test cluster. This change add a job on macos-14[1], running the flake8,
pylint, and black. This will help developers to validate changes on
macOS without access to macOS machine.

More work is needed to filter out the test that require a test cluster.

[1] https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

2024-09-18 23:20 UTC, nirs commented on .github/workflows/ci.yaml
> +          - macos-14
This is a VM on M1 machine, so it does not support nested virtualization. We can try to use macos-13 (x86 vm). It it support nested virtualization we can run lima vm and run all tests.

2024-09-19 16:42 UTC, nirs commented on .github/workflows/ci.yaml
> +          - macos-14
We can use `macos-13` which is intel machine and it support nested virtualization:
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#viewing-available-runners-for-a-repository

lima uses this to run vms on github:
https://github.com/lima-vm/lima/blob/master/.github/workflows/test.yml#L404

2024-11-20 15:48 UTC, raghavendra-talur requested changes
The changes themselves look good to me but the ci.yaml file has become too long now.

Please move the ramenctl and drenv tests to a different workflow file.

2024-11-20 15:57 UTC, nirs commented
> The changes themselves look good to me but the ci.yaml file has become too long now.
> 
> Please move the ramenctl and drenv tests to a different workflow file.

Good idea, moving

2024-11-20 18:49 UTC, raghavendra-talur commented
@nirs I will merge this once you move it out of draft.

2024-11-21 08:00 UTC, merged