e2e: Improve discovered apps infrastructure
RamenDR/ramen pull request #1706
Opened 2024-12-08 21:52 UTC by nirs

- Add types.Deployer.IsDicovered()
- Improve names for discovered apps

2024-12-09 16:53 UTC, raghavendra-talur requested changes

2024-12-09 16:53 UTC, raghavendra-talur commented on e2e/util/const.go
> +	RamenOpsNammespace = "ramen-ops"
s/RamenOpsNammespace/RamenOpsNamespace/g

2024-12-09 16:58 UTC, nirs commented
> @nirs I agree with the overall idea. There is one typo that needs to be fixed.
> 
> I am still debating if we should have a function in the interface that returns bool for discovered or just have a function called deployerType and returns a string. However, we can merge this and make changes later if we think the other way is better.

Since this is not an API, we can use a bool now an change this later in the unlikely case that there will be another strange deployer which is not discovered.

2024-12-09 18:32 UTC, nirs commented
@raghavendra-talur should be ready when the e2e job completes.

2024-12-11 21:35 UTC, raghavendra-talur approved these changes

2024-12-11 21:35 UTC, merged