create RS irrespective of PV mount status.
RamenDR/ramen pull request #1724
Opened 2024-12-12 17:36 UTC by pruthvitd

Fix for [[2319824] [RDR] Replication via Volsync requires PVC to be mounted before PVC is synchronized](https://issues.redhat.com/browse/DFBUGS-580)
	Create ReplicationSource irrespective of PV being mounted to running pod.

2024-12-12 17:42 UTC, pruthvitd commented
## How this is tested:
```
(ramen) [root@ramen1 samples]# kubectl scale deployment/busybox --replicas=0 -n deployment-cephfs --context dr1
deployment.apps/busybox scaled
(ramen) [root@ramen1 samples]# kubectl get replicationsource -A --context dr1
NAMESPACE           NAME          SOURCE        LAST SYNC              DURATION        NEXT SYNC
deployment-cephfs   busybox-pvc   busybox-pvc   2024-12-12T16:54:40Z   40.696555939s   2024-12-12T16:55:00Z
(ramen) [root@ramen1 samples]# kubectl delete replicationsource busybox-pvc -n deployment-cephfs  --context dr1
replicationsource.volsync.backube "busybox-pvc" deleted
(ramen) [root@ramen1 samples]# kubectl get po -n deployment-cephfs --context dr1
NAME                                      READY   STATUS    RESTARTS   AGE
volsync-rsync-tls-src-busybox-pvc-5kb8n   0/1     Pending   0          1s
(ramen) [root@ramen1 samples]# kubectl get po -n deployment-cephfs --context dr1
No resources found in deployment-cephfs namespace.
(ramen) [root@ramen1 samples]# kubectl get replicationsource -A --context dr1
NAMESPACE           NAME          SOURCE        LAST SYNC              DURATION        NEXT SYNC
deployment-cephfs   busybox-pvc   busybox-pvc   2024-12-12T16:57:34Z   34.517990544s   2024-12-12T16:58:00Z
```

#### ramen-dr-cluster-operator pod log:
```# kubectl logs -f ramen-dr-cluster-operator-74f89d85d7-h4k45 -n ramen-system --context dr1 >> /root/DR/samples/dr1-ramen.log &
[1] 588806
(ramen) [root@ramen1 ramen]# grep "PVC is not in use by ready pod, yet creating RS ..." /root/DR/samples/dr1-ramen.log
2024-12-12T16:55:11.923Z	INFO	controllers.VolumeReplicationGroup	volsync/vshandler.go:399	PVC is not in use by ready pod, yet creating RS ...	{"VolumeReplicationGroup": {"name":"deployment-cephfs-drpc","namespace":"deployment-cephfs"}, "rid": "14afb717-e7a4-4367-a85c-b31b207693a6", "rsSpec": {"protectedPVC":{"namespace":"deployment-cephfs","name":"busybox-pvc","protectedByVolSync":true,"storageID":{"id":""},"replicationID":{"id":""},"storageClassName":"rook-cephfs","annotations":{"apps.open-cluster-management.io/hosting-subscription":"deployment-cephfs/subscription","apps.open-cluster-management.io/reconcile-option":"merge"},"labels":{"app":"deployment-cephfs","app.kubernetes.io/part-of":"deployment-cephfs","appname":"busybox"},"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}},"conditions":[{"type":"ReplicationSourceSetup","status":"True","observedGeneration":1,"lastTransitionTime":"2024-12-12T16:37:47Z","reason":"SourceInitialized","message":"Ready"}],"volumeMode":"Filesystem"}}, "runFinalSync": false}
```

2024-12-12 21:35 UTC, BenamarMk commented on internal/controller/volsync/vshandler.go
>  		}
I would just replace all lines from line 370 to 399 and replace it with this:
```
_, err := v.getRS(getReplicationSourceName(rsSpec.ProtectedPVC.Name), rsSpec.ProtectedPVC.Namespace)
if err != nil {
    if !kerrors.IsNotFound(err) {
        return false, err
    }
}

return true, nil
```

2024-12-16 18:08 UTC, BenamarMk commented on internal/controller/volsync/vshandler.go
> +		l.Info("ReplicationSource does not exist, creating it now. ")
If you want to log here, just say "**ReplicationSource does not exist**". If you say "creating it now" it implies that this function will create it.  But this function does do that.  So I would ignore that part.

2024-12-16 22:07 UTC, raghavendra-talur requested changes

2024-12-16 22:07 UTC, raghavendra-talur commented on internal/controller/volsync/vshandler.go
>  	}
return false,nil case is missing?

2024-12-16 22:07 UTC, raghavendra-talur commented on internal/controller/volsync/vshandler_test.go
> -				Context("When no running pod is mounting the PVC to be protected", func() {
Instead of deleting this case, I suggest inverting the expectation. Ensure that a RS is created even in this case.

2024-12-17 05:55 UTC, raghavendra-talur approved these changes

2024-12-17 05:55 UTC, raghavendra-talur commented on internal/controller/volsync/vshandler.go
>  	}
Verified that false, nil case isn't required here. We are returning true, nil for two cases
1. rs is not found
2. rs is found

Only when an error is encountered, we return false, err

2024-12-17 08:39 UTC, ELENAGER approved these changes
LGTM

2024-12-17 12:14 UTC, BenamarMk commented on internal/controller/volsync/vshandler.go
>  	// the PVC and is in "Running" state before attempting to create an RS.
This entire comment block needs to change.

2024-12-17 16:53 UTC, BenamarMk commented on internal/controller/volsync/vshandler.go
> +	l.Info("Good to proceed with final sync.")
Maybe just remove this

2024-12-17 16:55 UTC, BenamarMk commented on internal/controller/volsync/vshandler.go
>  func (v *VSHandler) validatePVCBeforeRS(rsSpec ramendrv1alpha1.VolSyncReplicationSourceSpec,
Maybe the function name should change to `validatePVCForFinalSync`

2024-12-18 13:26 UTC, BenamarMk approved these changes
LGTM.
Thanks @pruthvitd

2024-12-18 13:58 UTC, merged