Improve error messages and logs when displaying cluster names
RamenDR/ramen pull request #806
Opened 2023-03-24 06:30 UTC by Shwetha-Acharya

Errors like "RuntimeError: Timeout waiting for cluster hub" can get confusing if a hub cluster is not named hub.

Resolve this issue with following improvisation:
RuntimeError: Timeout waiting for cluster 'hub'

Apply the same for all the instances cluster names in errors and logs.

Fixes: #795

2023-03-26 10:32 UTC, nirs commented
The changes look good - since we always quote strings, using "{var!r}" is less clear
than the simple f"'{var}'".

I tested this using:
```
$ drenv start regional-dr.yaml -v >regional-dr.log 2>&1
```

Looking for unquoted cluster names:
```
$ egrep '\[(hub|dr1|dr2)/[0-9]\] .* (hub|dr1|dr2)\b' regional-dr.log
2023-03-26 13:17:23,704 DEBUG   [hub/0] Initializing hub
2023-03-26 13:18:10,237 DEBUG   [hub/0] The multicluster hub control plane has been initialized successfully!
2023-03-26 13:18:10,237 DEBUG   [hub/0] You can now register cluster(s) to the hub control plane. Log onto those cluster(s) and run the following command:
2023-03-26 13:18:10,240 DEBUG   [hub/0] Installing hub addons
2023-03-26 13:18:11,367 DEBUG   [dr2/1] Joining to cluster hub
2023-03-26 13:18:11,381 DEBUG   [dr1/1] Joining to cluster hub
2023-03-26 13:20:11,883 DEBUG   [dr1/1] Please log onto the hub cluster and run the following command:
2023-03-26 13:20:11,883 DEBUG   [dr1/1]     clusteradm accept --clusters dr1
2023-03-26 13:20:11,944 DEBUG   [dr1/1] Starting approve csrs for the cluster dr1
2023-03-26 13:20:11,953 DEBUG   [dr1/1] CSR dr1-vbl9z approved
2023-03-26 13:20:11,978 DEBUG   [dr1/1] set hubAcceptsClient to true for managed cluster dr1
2023-03-26 13:20:11,979 DEBUG   [dr1/1]  Your managed cluster dr1 has joined the Hub successfully. Visit https://open-cluster-management.io/scenarios or https://github.com/open-cluster-management-io/OCM/tree/main/solutions for next steps.
2023-03-26 13:20:12,201 DEBUG   [dr1/1] Deploying application-manager add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr1.
2023-03-26 13:20:12,601 DEBUG   [dr1/1] Deploying config-policy-controller add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr1.
2023-03-26 13:20:22,809 DEBUG   [dr1/1] Deploying governance-policy-framework add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr1.
2023-03-26 13:20:32,981 DEBUG   [dr1/1] Deploying work-manager add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr1.
2023-03-26 13:20:39,372 DEBUG   [dr2/1] Please log onto the hub cluster and run the following command:
2023-03-26 13:20:39,372 DEBUG   [dr2/1]     clusteradm accept --clusters dr2
2023-03-26 13:20:39,413 DEBUG   [dr2/1] Starting approve csrs for the cluster dr2
2023-03-26 13:20:39,422 DEBUG   [dr2/1] CSR dr2-7652m approved
2023-03-26 13:20:39,451 DEBUG   [dr2/1] set hubAcceptsClient to true for managed cluster dr2
2023-03-26 13:20:39,451 DEBUG   [dr2/1]  Your managed cluster dr2 has joined the Hub successfully. Visit https://open-cluster-management.io/scenarios or https://github.com/open-cluster-management-io/OCM/tree/main/solutions for next steps.
2023-03-26 13:20:39,636 DEBUG   [dr2/1] Deploying application-manager add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
2023-03-26 13:20:40,017 DEBUG   [dr2/1] Deploying config-policy-controller add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
2023-03-26 13:20:50,223 DEBUG   [dr2/1] Deploying governance-policy-framework add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
2023-03-26 13:21:00,420 DEBUG   [dr2/1] Deploying work-manager add-on to namespaces open-cluster-management-agent-addon of managed cluster: dr2.
```

These lines are from underlying tools (e.g. clusteradm) that we cannot fix, but I think 
these lines can be fixed:

```
2023-03-26 13:18:11,367 DEBUG   [dr2/1] Joining to cluster hub
2023-03-26 13:18:11,381 DEBUG   [dr1/1] Joining to cluster hub
```

While fixing quoting, we can also remove the 'to' to make it:

    Joining cluster 'hub'

2023-03-26 10:34 UTC, nirs requested changes
Need to quote `Joining to cluster hub`

2023-03-26 10:52 UTC, nirs commented
Another test, testing error message - I added this bug:
```
$ git diff
diff --git a/test/ocm-cluster/start b/test/ocm-cluster/start
index 5b0ede0..4345457 100755
--- a/test/ocm-cluster/start
+++ b/test/ocm-cluster/start
@@ -92,11 +92,11 @@ def join_cluster(cluster, hub):
     clusteradm.join(
         hub_token=hub_info["hub-token"],
         hub_apiserver=hub_info["hub-apiserver"],
         cluster_name=cluster,
         wait=True,
-        context=cluster,
+        context=cluster + "-missing",
     )
 
 
 def accept_cluster(cluster, hub):
     print("Accepting cluster")
```

And started the ocm.yaml:
```
$ drenv start ocm.yaml 
```

The error message is generated by the underling tool that we don't control:

```
            E0326 13:40:08.778010  472328 exec.go:105] Failed building kube client: context "dr2-missing" does not exist
            Error: context "dr2-missing" does not exist
```

Checking for unquoted code:
```
$ git grep -n ' {hub}'
ocm-cluster/start:87:    print(f"Joining to cluster {hub}")

$ git grep -n ' {cluster}'
rbd-mirror/start:64:    print(f"Configure peers for cluster {cluster}")
rbd-mirror/start:84:    print(f"Waiting until ceph mirror daemon is healthy in cluster {cluster}")
```

2023-03-27 14:12 UTC, nirs approved these changes
Thanks!

2023-03-28 10:27 UTC, rakeshgm approved these changes

2023-03-28 10:27 UTC, merged