Delete failed backups
RamenDR/ramen pull request #874
Opened 2023-05-06 00:35 UTC by hatfieldbrian

# Problem
If a normal backup or hook backup, but not a dummy back, fails or partially fails then its request is deleted but its object store objects are not.  Subsequent retries fails due to backup already existing.

# Solution
If a backup fails or partially fails, delete backup in addition to its request.
-  Backup deletion is done via Ramen's s3 utility interface as it is synchronous
   - Velero's undocumented `DeleteBackupRequest` API requires managing another object asynchronously, one that deletes itself on successful completion
- Use results from existing in-progress `Backup` and `Restore` request queries instead of re-querying them in velero driver

Note: A misbehaved application could result in backups being deleted wowever, it must have permission to delete from the s3 bucket to do so.

Closes #807 

## End-to-end test results

```sh
$ kubectl logs -nvelero deploy/velero --context cluster2
$ hack/minikube-ramen.sh manager_log cluster2
```

Hook 1 fails due to issue #869 
```
time="2023-05-05T21:50:33Z" level=info msg="running exec hook" backup=velero/asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2 hookCommand="[date]" hookContainer=busybox hookName=date hookOnError=Fail hookPhase=post hookSource=backupSpec hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:126" name=busybox-75666c475f-x62kg namespace=asdf resource=pods
time="2023-05-05T21:50:33Z" level=info msg="stdout: " backup=velero/asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2 hookCommand="[date]" hookContainer=busybox hookName=date hookOnError=Fail hookPhase=post hookSource=backupSpec hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:173" name=busybox-75666c475f-x62kg namespace=asdf resource=pods
time="2023-05-05T21:50:33Z" level=info msg="stderr: " backup=velero/asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2 hookCommand="[date]" hookContainer=busybox hookName=date hookOnError=Fail hookPhase=post hookSource=backupSpec hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:174" name=busybox-75666c475f-x62kg namespace=asdf resource=pods
time="2023-05-05T21:50:33Z" level=error msg="Error executing hook" backup=velero/asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2 error="unable to upgrade connection: container not found (\"busybox\")" hookPhase=post hookSource=backupSpec hookType=exec logSource="internal/hook/item_hook_handler.go:248" name=busybox-75666c475f-x62kg namespace=asdf resource=pods

2023-05-05T21:50:34.882Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:582      backup: use-backup-not-restore-restore-2, captureToRecoverFrom: 1       {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary"}
2023-05-05T21:50:34.882Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:676  Backup  {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary", "phase": "PartiallyFailed", "warnings": 0, "errors": 1, "failure": "", "validation errors": []}
2023-05-05T21:50:34.882Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:685  Backup  {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary", "start": "2023-05-05 21:50:33 +0000 UTC"}
2023-05-05T21:50:34.882Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:689  Backup  {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary", "finish": "2023-05-05 21:50:33 +0000 UTC"}
2023-05-05T21:50:34.882Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:693  Items   {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary", "to be backed up": 1, "backed up": 1}
2023-05-05T21:50:34.882Z        ERROR   controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:662      Kube objects group recover error        {"VolumeReplicationGroup": "asdf/bb", "rid": "70219aac-116d-4349-80f2-b81689e4d033", "State": "primary", "number": 1, "profile": "minio-on-cluster2", "group": 2, "name": "use-backup-not-restore", "error": "backupPartiallyFailed"}
```
Manually create VR to workaround issue #869

Hook 1 succeeds
```
2023-05-05T21:50:34.997Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:582      backup: use-backup-not-restore-restore-2, captureToRecoverFrom: 1       {"VolumeReplicationGroup": "asdf/bb", "rid": "96536e2e-d343-4787-bccd-244404b8bb88", "State": "primary"}
2023-05-05T21:50:34.997Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:331  Kube objects protect    {"VolumeReplicationGroup": "asdf/bb", "rid": "96536e2e-d343-4787-bccd-244404b8bb88", "State": "primary", "s3 url": "http://192.168.39.123:30000", "s3 bucket": "bucket", "s3 region": "us-east-1", "s3 key prefix": "asdf/bb/kube-objects/0/", "secret key ref": "&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:s3secret,},Key:aws,Optional:nil,}", "source namespace": "asdf", "request namespace": "velero", "capture name": "asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2", "label set": {"ramendr.openshift.io/owner-name":"bb","ramendr.openshift.io/owner-namespace-name":"asdf"}, "annotations": {}}
2023-05-05T21:50:35.001Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:556  Object created successfully     {"VolumeReplicationGroup": "asdf/bb", "rid": "96536e2e-d343-4787-bccd-244404b8bb88", "State": "primary", "type": "&TypeMeta{Kind:,APIVersion:,}", "name": "asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2"}
2023-05-05T21:50:35.009Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:644      Kube objects group recover request submitted    {"VolumeReplicationGroup": "asdf/bb", "rid": "96536e2e-d343-4787-bccd-244404b8bb88", "State": "primary", "number": 1, "profile": "minio-on-cluster2", "group": 2, "name": "use-backup-not-restore"}
2023-05-05T21:50:35.009Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_volrep.go:1725  failed to restore PVs and PVCs using profile list ([minio-on-cluster2 minio-on-cluster1])       {"VolumeReplicationGroup": "asdf/bb", "rid": "96536e2e-d343-4787-bccd-244404b8bb88", "State": "primary"}

2023-05-05T21:50:35.258Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:582      backup: use-backup-not-restore-restore-2, captureToRecoverFrom: 1       {"VolumeReplicationGroup": "asdf/bb", "rid": "878abf7f-cf60-4bba-bad2-a4e69c5c3b97", "State": "primary"}
2023-05-05T21:50:35.258Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:676  Backup  {"VolumeReplicationGroup": "asdf/bb", "rid": "878abf7f-cf60-4bba-bad2-a4e69c5c3b97", "State": "primary", "phase": "InProgress", "warnings": 0, "errors": 0, "failure": "", "validation errors": []}
2023-05-05T21:50:35.259Z        INFO    controllers.VolumeReplicationGroup.vrginstance  velero/requests.go:685  Backup  {"VolumeReplicationGroup": "asdf/bb", "rid": "878abf7f-cf60-4bba-bad2-a4e69c5c3b97", "State": "primary", "start": "2023-05-05 21:50:35 +0000 UTC"}
2023-05-05T21:50:35.259Z        INFO    controllers.VolumeReplicationGroup.vrginstance  controllers/vrg_kubeobjects.go:660      Kube objects group recovering   {"VolumeReplicationGroup": "asdf/bb", "rid": "878abf7f-cf60-4bba-bad2-a4e69c5c3b97", "State": "primary", "number": 1, "profile": "minio-on-cluster2", "group": 2, "name": "use-backup-not-restore", "state": "backupInProgress"}

time="2023-05-05T21:50:35Z" level=info msg="running exec hook" backup=velero/asdf--bb--0--use-backup-not-restore-restore-2--minio-on-cluster2 hookComma [...]

2023-05-26 00:47 UTC, tjanssen3 approved these changes
Walked through the changes with Brian earlier this week, and tested the changes against scripts using a Recipe, and not using a Recipe. Looks good to me.

2023-07-27 13:59 UTC, ELENAGER commented on controllers/vrg_kubeobjects.go
> +			return
Maybe proceed to the next group? I mean, continue instead of return here?

2023-08-01 15:06 UTC, raghavendra-talur requested changes

2023-08-01 15:07 UTC, raghavendra-talur commented
@hatfieldbrian Can you please add one line explanation to the commits and also a abstract for the PR?

I am not sure of all the changes that are being made.

2023-08-03 14:01 UTC, hatfieldbrian commented on hack/shio-demo.sh
> +	      - "rm /tmp/a||! touch /tmp/a"
It passes shellcheck!

2023-08-03 16:21 UTC, hatfieldbrian commented
> @hatfieldbrian Can you please add one line explanation to the commits and also a abstract for the PR?
> 
> I am not sure of all the changes that are being made.

@raghavendra-talur Description updated with implementation details including descriptions of each commit

2023-08-22 15:09 UTC, raghavendra-talur approved these changes

2023-08-22 15:09 UTC, raghavendra-talur approved these changes

2023-09-01 00:04 UTC, hatfieldbrian commented
Two reviewers approved this one.  Would someone be willing to merge it?

2023-09-05 17:20 UTC, merged